# golang.org/x/text/gen.go imports this package; we don't depend on it.
ignored = ["golang.org/x/text/collate"]

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.15.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  branch = "master"
  name = "upspin.io"

[prune]
  non-go = true
  unused-packages = true
  go-tests = true

